- hosts: appserver
  become: yes
  
  tasks:
    - name: Changing permissions to script
      shell: chmod u+x ../docker-pulling-image.sh
    
    - name: Executing the script
      shell: ../docker-pulling-image.sh