- hosts: appserver
  become: yes
  

  tasks:
    - name: Changing permissions to script
      file: 
        path: /home/ubuntu/jenkins/workspace/deploying-petclinic/ansible/docker-pulling-image.sh
        mode: u+x
    
    - name: Executing the script
      script: /home/ubuntu/jenkins/workspace/deploying-petclinic/ansible/docker-pulling-image.sh