- hosts: appserver
  become: yes
  

  tasks:
    - name: Changing permissions to script
      cmd: chmod u+x /home/ubuntu/jenkins/workspace/deploying-petclinic/ansible/docker-pulling-image.sh
    
    - name: Executing the script
      cmd: /home/ubuntu/jenkins/workspace/deploying-petclinic/ansible/docker-pulling-image.sh