- hosts: appserver
  become: yes
  
  tasks:
    - name: Copy script
      copy:
        src: p/home/ubuntu/jenkins/workspace/deploying-petclinic/ansible/docker-pulling-image.sh
        dest: /tmp/docker-pulling-image.sh
        mode: u+x
    
    - name: Executing the script
      script: /tmp/ansible/docker-pulling-image.sh